
# SEO settings
title: Maurício Aniche
description: "Maurício Aniche, Assistant Professor in Software Engineering at TU Delft"
keywords: "mauricio aniche, aniche, tudelft, tu delft, software engineering, research"
url: http://www.mauricioaniche.com

google_analytics: UA-10934071-4

# Build settings
markdown    : kramdown
highlighter : rouge

collections:
  publications:
    permalink: /:collection/:title/
    output: true
  talks:
    permalink: /:collection/:title/
    output: true
  blog:
    permalink: /:collection/:title/
    output: true
    
defaults:
  - scope:
      path: ""
      type: "publications"
    values:
      layout: "publication"

destination: _site

# Sass configuration
sass:
  sass_dir: assets/_sass
  style: compressed # expanded

# Author settings
author:
  name     : Maurício Aniche
  firstname: Maurício
  surname  : Aniche
  thumb    : /assets/images/photo.jpg
  email    : mauricioaniche@gmail.com
  url      : http://www.mauricioaniche.com
  github   : http://github.com/mauricioaniche
  twitter  : http://twitter.com/mauricioaniche
  linkedin : http://linkedin.com/in/mauricioaniche


exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
